CREATE OR REPLACE TABLE PEOPLE_VEHICLES AS
(SELECT
 CP.PERSON_ID
,CP.PERSON_TYPE
,CP.CRASH_RECORD_ID
,CP.VEHICLE_ID
,CV.VEHICLE_TYPE
,TO_DATE(TRY_TO_TIMESTAMP(CP.CRASH_DATE, 'MM/DD/YYYY HH12:MI:SS AM')) AS CRASH_DATE 
,TO_TIME(TRY_TO_TIMESTAMP(CP.CRASH_DATE, 'MM/DD/YYYY HH12:MI:SS AM')) AS CRASH_TIME
,CP.CITY
,CP.STATE
,CP.ZIPCODE
,CP.SEX 
,TRY_CAST(CP.AGE AS INTEGER) AS AGE
,TRY_CAST(CV.VEHICLE_YEAR AS INTEGER) AS VEHICLE_YEAR
,CASE
WHEN TRY_CAST(CV.VEHICLE_YEAR AS INTEGER) < 2018 THEN 'OLDER VEHICLE'
WHEN TRY_CAST(CV.VEHICLE_YEAR AS INTEGER) <= 2023 THEN 'NEW VEHICLE'
ELSE 'UNKNOWN'
END AS VEHICLE_AGE
FROM CRASHES_PEOPLE AS CP
LEFT JOIN CRASHES_VEHICLES AS CV 
ON CP.VEHICLE_ID = CV.VEHICLE_ID 
AND CP.CRASH_RECORD_ID = CV.CRASH_RECORD_ID
AND CV.UNIT_TYPE = 'DRIVER'
AND CV.UNIT_NO = 1
INNER JOIN CRASHES AS CR ON
CR.CRASH_RECORD_ID = CP.CRASH_RECORD_ID
WHERE CP.PERSON_TYPE = 'DRIVER'
)
;
